name: Build Solution

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build solution
        run: gcc -o 1.exe Windows_AFD_LPE_CVE-2023-21768/exploit.c
        
      - name: tar
        run: tar -cvf te.tar ./*

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file:  te.tar
          tag: ${{ github.ref }}
          release_name: ${{ github.ref }}
          overwrite: true
          file_glob: true
          body: ""
