name: Build Solution

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up MSVC environment
        uses: microsoft/setup-msvc@v1.8.2
        with:
          msvc-version: 'latest'

      - name: Restore NuGet packages
        run: nuget restore

      - name: Build solution
        run: msbuild /t:build /p:Configuration=Release /p:Platform=x64
        
      - name: tar
        run: tar -cvf te.tar ./*

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file:  te.tar
          tag: ${{ github.ref }}
          release_name: ${{ github.ref }}
          overwrite: true
          file_glob: true
          body: ""
