# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up MSVC environment
        uses: microsoft/setup-msvc@v1.8.2
        with:
          msvc-version: 'latest'

      - name: Install Windows SDK
        run: |
          choco install windows-sdk-10.0
          refreshenv

      - name: Compile project
        run: cl.exe /EHsc /I C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0 /c Windows_AFD_LPE_CVE-2023-21768/exploit.c

      - name: Link project
        run: link.exe /OUT:main.exe main.obj
        
      - name: out
        run: tree
        
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: main.exe
          tag: ${{ github.ref }}
          release_name: ${{ github.ref }}
          overwrite: true
          file_glob: true
          body: ""

      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Release build
          path: main.exe

